# Diagrams of various activation functions available in Keras

In [1]:
#@title Imports and utilities {display-mode: "form"}


import tensorflow as tf
from tensorflow import keras
from tensorflow.python.keras import backend as K
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import math_ops

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn as sk
import numpy as np
import functools
import itertools
import time
import os
import datetime
import altair as alt

print([tf.__version__, pd.__version__, sns.__version__ ,plt.matplotlib.__version__,np.__version__])

from IPython.core.pylabtools import figsize
figsize(12.5, 3)

# Display training progress by printing a single dot for each completed epoch
class PrintDot(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, logs):
    if epoch % 100 == 0: print('')
    print('.', end='')

early_stop = keras.callbacks.EarlyStopping(monitor='val_loss', patience=50, min_delta=0.001, verbose=1)
terminate_nan = keras.callbacks.TerminateOnNaN()

def plot_history(history):
    hist = pd.DataFrame(history.history)
    hist['epoch'] = history.epoch

    plt.figure()
    plt.xlabel('Epoch')
    plt.ylabel('Val Loss')
    plt.semilogy(hist['epoch'], hist['loss'], label='Train Error')
    plt.plot(hist['epoch'], hist['val_loss'], label='Val Error')
    # plt.ylim([0,5])
    plt.legend()
    
def meanAndVariance(y_true, y_pred):
  y_pred = tf.convert_to_tensor(y_pred)
  y_true = math_ops.cast(y_true, y_pred.dtype)
  means = y_pred[..., 0::2]
  variances = y_pred[..., 1::2]
  res = K.square(means - y_true) + K.square(variances - K.square(means - y_true))
  return K.mean(res, axis=-1)

def nans(ds):
  return ds.loc[ds.isna().any(axis=1)]

%config IPCompleter.greedy=True

['1.14.0', '0.24.2', '0.9.0', '3.0.3', '1.16.4']


In [0]:
tf.enable_eager_execution()

In [0]:
x = tf.constant(np.asarray(range(-1000,1000,5))/100.0)
xp = tf.constant(np.asarray([-10.0,-1.0,0.0,1.0,10.0]))

In [0]:
def plotfun(f):
  yp=f(xp).numpy()
  print(yp)
  y=f(x)
  return alt.Chart(pd.DataFrame({'x':x.numpy(), 'y':y.numpy()})).mark_line().encode(
      x='x',
      y='y',
  )

#plotfun(tf.nn.sigmoid)

In [5]:
plotfun(tf.nn.sigmoid)

[4.53978687e-05 2.68941421e-01 5.00000000e-01 7.31058579e-01
 9.99954602e-01]


Chart({
  data:          x         y
  0   -10.00  0.000045
  1    -9.95  0.000048
  2    -9.90  0.000050
  3    -9.85  0.000053
  4    -9.80  0.000055
  5    -9.75  0.000058
  6    -9.70  0.000061
  7    -9.65  0.000064
  8    -9.60  0.000068
  9    -9.55  0.000071
  10   -9.50  0.000075
  11   -9.45  0.000079
  12   -9.40  0.000083
  13   -9.35  0.000087
  14   -9.30  0.000091
  15   -9.25  0.000096
  16   -9.20  0.000101
  17   -9.15  0.000106
  18   -9.10  0.000112
  19   -9.05  0.000117
  20   -9.00  0.000123
  21   -8.95  0.000130
  22   -8.90  0.000136
  23   -8.85  0.000143
  24   -8.80  0.000151
  25   -8.75  0.000158
  26   -8.70  0.000167
  27   -8.65  0.000175
  28   -8.60  0.000184
  29   -8.55  0.000194
  ..     ...       ...
  370   8.50  0.999797
  371   8.55  0.999806
  372   8.60  0.999816
  373   8.65  0.999825
  374   8.70  0.999833
  375   8.75  0.999842
  376   8.80  0.999849
  377   8.85  0.999857
  378   8.90  0.999864
  379   8.95  0.999870
  380   9.00  0.999877
  381   9.05  0.999883
  382   9.10  0.999888
  383   9.15  0.999894
  384   9.20  0.999899
  385   9.25  0.999904
  386   9.30  0.999909
  387   9.35  0.999913
  388   9.40  0.999917
  389   9.45  0.999921
  390   9.50  0.999925
  391   9.55  0.999929
  392   9.60  0.999932
  393   9.65  0.999936
  394   9.70  0.999939
  395   9.75  0.999942
  396   9.80  0.999945
  397   9.85  0.999947
  398   9.90  0.999950
  399   9.95  0.999952
  
  [400 rows x 2 columns],
  encoding: FacetedEncoding({
    x: X({
      field: 'x',
      type: 'quantitative'
    }),
    y: Y({
      field: 'y',
      type: 'quantitative'
    })
  }),
  mark: 'line'
})

In [6]:
plotfun( tf.nn.softsign )

[-0.90909091 -0.5         0.          0.5         0.90909091]


Chart({
  data:          x         y
  0   -10.00 -0.909091
  1    -9.95 -0.908676
  2    -9.90 -0.908257
  3    -9.85 -0.907834
  4    -9.80 -0.907407
  5    -9.75 -0.906977
  6    -9.70 -0.906542
  7    -9.65 -0.906103
  8    -9.60 -0.905660
  9    -9.55 -0.905213
  10   -9.50 -0.904762
  11   -9.45 -0.904306
  12   -9.40 -0.903846
  13   -9.35 -0.903382
  14   -9.30 -0.902913
  15   -9.25 -0.902439
  16   -9.20 -0.901961
  17   -9.15 -0.901478
  18   -9.10 -0.900990
  19   -9.05 -0.900498
  20   -9.00 -0.900000
  21   -8.95 -0.899497
  22   -8.90 -0.898990
  23   -8.85 -0.898477
  24   -8.80 -0.897959
  25   -8.75 -0.897436
  26   -8.70 -0.896907
  27   -8.65 -0.896373
  28   -8.60 -0.895833
  29   -8.55 -0.895288
  ..     ...       ...
  370   8.50  0.894737
  371   8.55  0.895288
  372   8.60  0.895833
  373   8.65  0.896373
  374   8.70  0.896907
  375   8.75  0.897436
  376   8.80  0.897959
  377   8.85  0.898477
  378   8.90  0.898990
  379   8.95  0.899497
  380   9.00  0.900000
  381   9.05  0.900498
  382   9.10  0.900990
  383   9.15  0.901478
  384   9.20  0.901961
  385   9.25  0.902439
  386   9.30  0.902913
  387   9.35  0.903382
  388   9.40  0.903846
  389   9.45  0.904306
  390   9.50  0.904762
  391   9.55  0.905213
  392   9.60  0.905660
  393   9.65  0.906103
  394   9.70  0.906542
  395   9.75  0.906977
  396   9.80  0.907407
  397   9.85  0.907834
  398   9.90  0.908257
  399   9.95  0.908676
  
  [400 rows x 2 columns],
  encoding: FacetedEncoding({
    x: X({
      field: 'x',
      type: 'quantitative'
    }),
    y: Y({
      field: 'y',
      type: 'quantitative'
    })
  }),
  mark: 'line'
})

In [7]:
plotfun( tf.nn.elu )

[-0.9999546  -0.63212056  0.          1.         10.        ]


Chart({
  data:          x         y
  0   -10.00 -0.999955
  1    -9.95 -0.999952
  2    -9.90 -0.999950
  3    -9.85 -0.999947
  4    -9.80 -0.999945
  5    -9.75 -0.999942
  6    -9.70 -0.999939
  7    -9.65 -0.999936
  8    -9.60 -0.999932
  9    -9.55 -0.999929
  10   -9.50 -0.999925
  11   -9.45 -0.999921
  12   -9.40 -0.999917
  13   -9.35 -0.999913
  14   -9.30 -0.999909
  15   -9.25 -0.999904
  16   -9.20 -0.999899
  17   -9.15 -0.999894
  18   -9.10 -0.999888
  19   -9.05 -0.999883
  20   -9.00 -0.999877
  21   -8.95 -0.999870
  22   -8.90 -0.999864
  23   -8.85 -0.999857
  24   -8.80 -0.999849
  25   -8.75 -0.999842
  26   -8.70 -0.999833
  27   -8.65 -0.999825
  28   -8.60 -0.999816
  29   -8.55 -0.999806
  ..     ...       ...
  370   8.50  8.500000
  371   8.55  8.550000
  372   8.60  8.600000
  373   8.65  8.650000
  374   8.70  8.700000
  375   8.75  8.750000
  376   8.80  8.800000
  377   8.85  8.850000
  378   8.90  8.900000
  379   8.95  8.950000
  380   9.00  9.000000
  381   9.05  9.050000
  382   9.10  9.100000
  383   9.15  9.150000
  384   9.20  9.200000
  385   9.25  9.250000
  386   9.30  9.300000
  387   9.35  9.350000
  388   9.40  9.400000
  389   9.45  9.450000
  390   9.50  9.500000
  391   9.55  9.550000
  392   9.60  9.600000
  393   9.65  9.650000
  394   9.70  9.700000
  395   9.75  9.750000
  396   9.80  9.800000
  397   9.85  9.850000
  398   9.90  9.900000
  399   9.95  9.950000
  
  [400 rows x 2 columns],
  encoding: FacetedEncoding({
    x: X({
      field: 'x',
      type: 'quantitative'
    }),
    y: Y({
      field: 'y',
      type: 'quantitative'
    })
  }),
  mark: 'line'
})

In [8]:
plotfun( tf.nn.relu )

[ 0.  0.  0.  1. 10.]


Chart({
  data:          x     y
  0   -10.00  0.00
  1    -9.95  0.00
  2    -9.90  0.00
  3    -9.85  0.00
  4    -9.80  0.00
  5    -9.75  0.00
  6    -9.70  0.00
  7    -9.65  0.00
  8    -9.60  0.00
  9    -9.55  0.00
  10   -9.50  0.00
  11   -9.45  0.00
  12   -9.40  0.00
  13   -9.35  0.00
  14   -9.30  0.00
  15   -9.25  0.00
  16   -9.20  0.00
  17   -9.15  0.00
  18   -9.10  0.00
  19   -9.05  0.00
  20   -9.00  0.00
  21   -8.95  0.00
  22   -8.90  0.00
  23   -8.85  0.00
  24   -8.80  0.00
  25   -8.75  0.00
  26   -8.70  0.00
  27   -8.65  0.00
  28   -8.60  0.00
  29   -8.55  0.00
  ..     ...   ...
  370   8.50  8.50
  371   8.55  8.55
  372   8.60  8.60
  373   8.65  8.65
  374   8.70  8.70
  375   8.75  8.75
  376   8.80  8.80
  377   8.85  8.85
  378   8.90  8.90
  379   8.95  8.95
  380   9.00  9.00
  381   9.05  9.05
  382   9.10  9.10
  383   9.15  9.15
  384   9.20  9.20
  385   9.25  9.25
  386   9.30  9.30
  387   9.35  9.35
  388   9.40  9.40
  389   9.45  9.45
  390   9.50  9.50
  391   9.55  9.55
  392   9.60  9.60
  393   9.65  9.65
  394   9.70  9.70
  395   9.75  9.75
  396   9.80  9.80
  397   9.85  9.85
  398   9.90  9.90
  399   9.95  9.95
  
  [400 rows x 2 columns],
  encoding: FacetedEncoding({
    x: X({
      field: 'x',
      type: 'quantitative'
    }),
    y: Y({
      field: 'y',
      type: 'quantitative'
    })
  }),
  mark: 'line'
})

In [9]:
plotfun( tf.nn.leaky_relu )

[-2.00000003 -0.2         0.          1.         10.        ]


Chart({
  data:          x     y
  0   -10.00 -2.00
  1    -9.95 -1.99
  2    -9.90 -1.98
  3    -9.85 -1.97
  4    -9.80 -1.96
  5    -9.75 -1.95
  6    -9.70 -1.94
  7    -9.65 -1.93
  8    -9.60 -1.92
  9    -9.55 -1.91
  10   -9.50 -1.90
  11   -9.45 -1.89
  12   -9.40 -1.88
  13   -9.35 -1.87
  14   -9.30 -1.86
  15   -9.25 -1.85
  16   -9.20 -1.84
  17   -9.15 -1.83
  18   -9.10 -1.82
  19   -9.05 -1.81
  20   -9.00 -1.80
  21   -8.95 -1.79
  22   -8.90 -1.78
  23   -8.85 -1.77
  24   -8.80 -1.76
  25   -8.75 -1.75
  26   -8.70 -1.74
  27   -8.65 -1.73
  28   -8.60 -1.72
  29   -8.55 -1.71
  ..     ...   ...
  370   8.50  8.50
  371   8.55  8.55
  372   8.60  8.60
  373   8.65  8.65
  374   8.70  8.70
  375   8.75  8.75
  376   8.80  8.80
  377   8.85  8.85
  378   8.90  8.90
  379   8.95  8.95
  380   9.00  9.00
  381   9.05  9.05
  382   9.10  9.10
  383   9.15  9.15
  384   9.20  9.20
  385   9.25  9.25
  386   9.30  9.30
  387   9.35  9.35
  388   9.40  9.40
  389   9.45  9.45
  390   9.50  9.50
  391   9.55  9.55
  392   9.60  9.60
  393   9.65  9.65
  394   9.70  9.70
  395   9.75  9.75
  396   9.80  9.80
  397   9.85  9.85
  398   9.90  9.90
  399   9.95  9.95
  
  [400 rows x 2 columns],
  encoding: FacetedEncoding({
    x: X({
      field: 'x',
      type: 'quantitative'
    }),
    y: Y({
      field: 'y',
      type: 'quantitative'
    })
  }),
  mark: 'line'
})

In [10]:
plotfun( tf.nn.selu )

[-1.75801952 -1.11133074  0.          1.05070099 10.50700987]


Chart({
  data:          x          y
  0   -10.00  -1.758020
  1    -9.95  -1.758015
  2    -9.90  -1.758011
  3    -9.85  -1.758007
  4    -9.80  -1.758002
  5    -9.75  -1.757997
  6    -9.70  -1.757992
  7    -9.65  -1.757986
  8    -9.60  -1.757980
  9    -9.55  -1.757974
  10   -9.50  -1.757968
  11   -9.45  -1.757961
  12   -9.40  -1.757954
  13   -9.35  -1.757946
  14   -9.30  -1.757939
  15   -9.25  -1.757930
  16   -9.20  -1.757922
  17   -9.15  -1.757913
  18   -9.10  -1.757903
  19   -9.05  -1.757893
  20   -9.00  -1.757882
  21   -8.95  -1.757871
  22   -8.90  -1.757860
  23   -8.85  -1.757847
  24   -8.80  -1.757834
  25   -8.75  -1.757821
  26   -8.70  -1.757806
  27   -8.65  -1.757791
  28   -8.60  -1.757776
  29   -8.55  -1.757759
  ..     ...        ...
  370   8.50   8.930958
  371   8.55   8.983493
  372   8.60   9.036028
  373   8.65   9.088564
  374   8.70   9.141099
  375   8.75   9.193634
  376   8.80   9.246169
  377   8.85   9.298704
  378   8.90   9.351239
  379   8.95   9.403774
  380   9.00   9.456309
  381   9.05   9.508844
  382   9.10   9.561379
  383   9.15   9.613914
  384   9.20   9.666449
  385   9.25   9.718984
  386   9.30   9.771519
  387   9.35   9.824054
  388   9.40   9.876589
  389   9.45   9.929124
  390   9.50   9.981659
  391   9.55  10.034194
  392   9.60  10.086729
  393   9.65  10.139265
  394   9.70  10.191800
  395   9.75  10.244335
  396   9.80  10.296870
  397   9.85  10.349405
  398   9.90  10.401940
  399   9.95  10.454475
  
  [400 rows x 2 columns],
  encoding: FacetedEncoding({
    x: X({
      field: 'x',
      type: 'quantitative'
    }),
    y: Y({
      field: 'y',
      type: 'quantitative'
    })
  }),
  mark: 'line'
})

In [11]:
plotfun( tf.nn.softplus )

[4.53988992e-05 3.13261688e-01 6.93147181e-01 1.31326169e+00
 1.00000454e+01]


Chart({
  data:          x         y
  0   -10.00  0.000045
  1    -9.95  0.000048
  2    -9.90  0.000050
  3    -9.85  0.000053
  4    -9.80  0.000055
  5    -9.75  0.000058
  6    -9.70  0.000061
  7    -9.65  0.000064
  8    -9.60  0.000068
  9    -9.55  0.000071
  10   -9.50  0.000075
  11   -9.45  0.000079
  12   -9.40  0.000083
  13   -9.35  0.000087
  14   -9.30  0.000091
  15   -9.25  0.000096
  16   -9.20  0.000101
  17   -9.15  0.000106
  18   -9.10  0.000112
  19   -9.05  0.000117
  20   -9.00  0.000123
  21   -8.95  0.000130
  22   -8.90  0.000136
  23   -8.85  0.000143
  24   -8.80  0.000151
  25   -8.75  0.000158
  26   -8.70  0.000167
  27   -8.65  0.000175
  28   -8.60  0.000184
  29   -8.55  0.000194
  ..     ...       ...
  370   8.50  8.500203
  371   8.55  8.550194
  372   8.60  8.600184
  373   8.65  8.650175
  374   8.70  8.700167
  375   8.75  8.750158
  376   8.80  8.800151
  377   8.85  8.850143
  378   8.90  8.900136
  379   8.95  8.950130
  380   9.00  9.000123
  381   9.05  9.050117
  382   9.10  9.100112
  383   9.15  9.150106
  384   9.20  9.200101
  385   9.25  9.250096
  386   9.30  9.300091
  387   9.35  9.350087
  388   9.40  9.400083
  389   9.45  9.450079
  390   9.50  9.500075
  391   9.55  9.550071
  392   9.60  9.600068
  393   9.65  9.650064
  394   9.70  9.700061
  395   9.75  9.750058
  396   9.80  9.800055
  397   9.85  9.850053
  398   9.90  9.900050
  399   9.95  9.950048
  
  [400 rows x 2 columns],
  encoding: FacetedEncoding({
    x: X({
      field: 'x',
      type: 'quantitative'
    }),
    y: Y({
      field: 'y',
      type: 'quantitative'
    })
  }),
  mark: 'line'
})

In [12]:
plotfun( tf.nn.tanh )

[-1.         -0.76159416  0.          0.76159416  1.        ]


Chart({
  data:          x    y
  0   -10.00 -1.0
  1    -9.95 -1.0
  2    -9.90 -1.0
  3    -9.85 -1.0
  4    -9.80 -1.0
  5    -9.75 -1.0
  6    -9.70 -1.0
  7    -9.65 -1.0
  8    -9.60 -1.0
  9    -9.55 -1.0
  10   -9.50 -1.0
  11   -9.45 -1.0
  12   -9.40 -1.0
  13   -9.35 -1.0
  14   -9.30 -1.0
  15   -9.25 -1.0
  16   -9.20 -1.0
  17   -9.15 -1.0
  18   -9.10 -1.0
  19   -9.05 -1.0
  20   -9.00 -1.0
  21   -8.95 -1.0
  22   -8.90 -1.0
  23   -8.85 -1.0
  24   -8.80 -1.0
  25   -8.75 -1.0
  26   -8.70 -1.0
  27   -8.65 -1.0
  28   -8.60 -1.0
  29   -8.55 -1.0
  ..     ...  ...
  370   8.50  1.0
  371   8.55  1.0
  372   8.60  1.0
  373   8.65  1.0
  374   8.70  1.0
  375   8.75  1.0
  376   8.80  1.0
  377   8.85  1.0
  378   8.90  1.0
  379   8.95  1.0
  380   9.00  1.0
  381   9.05  1.0
  382   9.10  1.0
  383   9.15  1.0
  384   9.20  1.0
  385   9.25  1.0
  386   9.30  1.0
  387   9.35  1.0
  388   9.40  1.0
  389   9.45  1.0
  390   9.50  1.0
  391   9.55  1.0
  392   9.60  1.0
  393   9.65  1.0
  394   9.70  1.0
  395   9.75  1.0
  396   9.80  1.0
  397   9.85  1.0
  398   9.90  1.0
  399   9.95  1.0
  
  [400 rows x 2 columns],
  encoding: FacetedEncoding({
    x: X({
      field: 'x',
      type: 'quantitative'
    }),
    y: Y({
      field: 'y',
      type: 'quantitative'
    })
  }),
  mark: 'line'
})

In [13]:
# some wild tries how to modify things

plotfun( lambda x : tf.nn.softsign((x-1)*5)*0.5+0.5 )

[0.00892857 0.04545455 0.08333333 0.5        0.98913043]


Chart({
  data:          x         y
  0   -10.00  0.008929
  1    -9.95  0.008969
  2    -9.90  0.009009
  3    -9.85  0.009050
  4    -9.80  0.009091
  5    -9.75  0.009132
  6    -9.70  0.009174
  7    -9.65  0.009217
  8    -9.60  0.009259
  9    -9.55  0.009302
  10   -9.50  0.009346
  11   -9.45  0.009390
  12   -9.40  0.009434
  13   -9.35  0.009479
  14   -9.30  0.009524
  15   -9.25  0.009569
  16   -9.20  0.009615
  17   -9.15  0.009662
  18   -9.10  0.009709
  19   -9.05  0.009756
  20   -9.00  0.009804
  21   -8.95  0.009852
  22   -8.90  0.009901
  23   -8.85  0.009950
  24   -8.80  0.010000
  25   -8.75  0.010050
  26   -8.70  0.010101
  27   -8.65  0.010152
  28   -8.60  0.010204
  29   -8.55  0.010256
  ..     ...       ...
  370   8.50  0.987013
  371   8.55  0.987097
  372   8.60  0.987179
  373   8.65  0.987261
  374   8.70  0.987342
  375   8.75  0.987421
  376   8.80  0.987500
  377   8.85  0.987578
  378   8.90  0.987654
  379   8.95  0.987730
  380   9.00  0.987805
  381   9.05  0.987879
  382   9.10  0.987952
  383   9.15  0.988024
  384   9.20  0.988095
  385   9.25  0.988166
  386   9.30  0.988235
  387   9.35  0.988304
  388   9.40  0.988372
  389   9.45  0.988439
  390   9.50  0.988506
  391   9.55  0.988571
  392   9.60  0.988636
  393   9.65  0.988701
  394   9.70  0.988764
  395   9.75  0.988827
  396   9.80  0.988889
  397   9.85  0.988950
  398   9.90  0.989011
  399   9.95  0.989071
  
  [400 rows x 2 columns],
  encoding: FacetedEncoding({
    x: X({
      field: 'x',
      type: 'quantitative'
    }),
    y: Y({
      field: 'y',
      type: 'quantitative'
    })
  }),
  mark: 'line'
})

In [15]:
def softsign01(x):
  """Variant of softsign that goes from 0 to 1"""
  return (tf.nn.softsign(x) + 1) / 2

plotfun(softsign01)

[0.04545455 0.25       0.5        0.75       0.95454545]


Chart({
  data:          x         y
  0   -10.00  0.045455
  1    -9.95  0.045662
  2    -9.90  0.045872
  3    -9.85  0.046083
  4    -9.80  0.046296
  5    -9.75  0.046512
  6    -9.70  0.046729
  7    -9.65  0.046948
  8    -9.60  0.047170
  9    -9.55  0.047393
  10   -9.50  0.047619
  11   -9.45  0.047847
  12   -9.40  0.048077
  13   -9.35  0.048309
  14   -9.30  0.048544
  15   -9.25  0.048780
  16   -9.20  0.049020
  17   -9.15  0.049261
  18   -9.10  0.049505
  19   -9.05  0.049751
  20   -9.00  0.050000
  21   -8.95  0.050251
  22   -8.90  0.050505
  23   -8.85  0.050761
  24   -8.80  0.051020
  25   -8.75  0.051282
  26   -8.70  0.051546
  27   -8.65  0.051813
  28   -8.60  0.052083
  29   -8.55  0.052356
  ..     ...       ...
  370   8.50  0.947368
  371   8.55  0.947644
  372   8.60  0.947917
  373   8.65  0.948187
  374   8.70  0.948454
  375   8.75  0.948718
  376   8.80  0.948980
  377   8.85  0.949239
  378   8.90  0.949495
  379   8.95  0.949749
  380   9.00  0.950000
  381   9.05  0.950249
  382   9.10  0.950495
  383   9.15  0.950739
  384   9.20  0.950980
  385   9.25  0.951220
  386   9.30  0.951456
  387   9.35  0.951691
  388   9.40  0.951923
  389   9.45  0.952153
  390   9.50  0.952381
  391   9.55  0.952607
  392   9.60  0.952830
  393   9.65  0.953052
  394   9.70  0.953271
  395   9.75  0.953488
  396   9.80  0.953704
  397   9.85  0.953917
  398   9.90  0.954128
  399   9.95  0.954338
  
  [400 rows x 2 columns],
  encoding: FacetedEncoding({
    x: X({
      field: 'x',
      type: 'quantitative'
    }),
    y: Y({
      field: 'y',
      type: 'quantitative'
    })
  }),
  mark: 'line'
})